name: Lint and Format Code

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint-and-format:
        name: Lint and Format
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: "latest"

            - name: Cache Bun Dependencies
              uses: actions/cache@v3
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json', '**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install

            - name: Run Linter
              run: bun run lint

            - name: Check Code Formatting
              run: bun run format --check
